version: "3.2"

services:
  ms:
    image: 927technology/ops:210430
    stdin_open: true
    tty: true 
    environment:
      - role=management
    hostname: ms
    volumes:
      - ./config/ms/etc/nagios:/etc/nagios
      - ./config/shared/usr/lib64/nagios/rw:/usr/lib64/nagios/rw
      - ./config/shared/var/spool/nagios:/var/spool/nagios
      - ./config/shared/var/log:/var/log
      - ./config/shared/usr/local/pnp4nagios/var/perfdata:/usr/local/pnp4nagios/var/perfdata
      - ./config/ms/etc/mod_gearman:/etc/mod_gearman
#  poller:
#    image: 927technology/ops:210430
#    stdin_open: true
#    tty: true 
#    environment:
#      - role=poller
#    hostname: trap
#    volumes:
#      - ./config/shared/var/spool/nagios:/var/spool/nagios
#      - ./config/shared/var/log:/var/log
#      - ./config/trap/etc/snmp/snmptrapd.conf:/etc/snmp/snmptrapd.conf
#      - ./config/trap/etc/snmp/snmptt.conf:/etc/snmp/snmptt.conf
  trap:
    image: 927technology/ops:210430
    stdin_open: true
    tty: true 
    environment:
      - role=trap
    hostname: trap
    ports:
      - 162:162/tcp
      - 162:162/udp
    volumes:
      - ./config/shared/var/spool/nagios:/var/spool/nagios
      - ./config/shared/var/log:/var/log
      - ./config/shared/var/spool/snmptt:/var/spool/snmptt
      - ./config/trap/etc/snmp:/etc/snmp
  web:
    image: 927technology/ops:210430
    stdin_open: true
    tty: true 
    environment:
      - role=web
    hostname: web
    ports:
      - 8000:80/tcp
    volumes:
      - ./config/shared/usr/lib64/nagios/rw:/usr/lib64/nagios/rw
      - ./config/web/etc/httpd/conf:/etc/httpd/conf
      - ./config/web/etc/httpd/conf.d:/etc/httpd/conf.d
      - ./config/shared/var/log:/var/log
      - ./config/shared/usr/local/pnp4nagios/var/perfdata:/usr/local/pnp4nagios/var/perfdata
      - ./config/web/etc/thruk:/etc/thruk
  wkr01:
    image: 927technology/ops:210430
    stdin_open: true
    tty: true 
    environment:
      - role=worker
    hostname: wkr01
    volumes:
      - ./config/shared/usr/lib64/nagios/plugins:/usr/lib64/nagios/plugins
      - ./config/shared/var/log:/var/log
      - ./config/wkr/etc/mod_gearman:/etc/mod_gearman
  wkr02:
    image: 927technology/ops:210430
    stdin_open: true
    tty: true 
    environment:
      - role=worker
    hostname: wkr02
    volumes:
      - ./config/shared/usr/lib64/nagios/plugins:/usr/lib64/nagios/plugins
      - ./config/shared/var/log:/var/log
      - ./config/wkr/etc/mod_gearman:/etc/mod_gearman
